name: flutter_mrz_scanner_enhanced
description: Scans MRZ (Machine Readable Zone) from identity documents for iOS and Android.
version: 3.0.0
homepage: https://github.com/ELMEHDAOUIAhmed/flutter_mrz_scanner_enhanced

environment:
  sdk: '>=2.17.6 <4.0.0'
  flutter: ">=3.0.5"

dependencies:
  flutter:
    sdk: flutter
  mrz_parser: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.github.ELMEHDAOUIAhmed.flutter_mrz_scanner_enhanced
        pluginClass: FlutterMrzScannerPlugin
      ios:
        pluginClass: FlutterMrzScannerPlugin